<?php
/**
 * GetCharactersCharacterIdWalletsJournal200OkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetCharactersCharacterIdWalletsJournal200OkTest Class Doc Comment
 *
 * @category    Class */
// * @description 200 ok object
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdWalletsJournal200OkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GetCharactersCharacterIdWalletsJournal200Ok"
     */
    public function testGetCharactersCharacterIdWalletsJournal200Ok()
    {

    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {

    }

    /**
     * Test attribute "argument_name"
     */
    public function testPropertyArgumentName()
    {

    }

    /**
     * Test attribute "argument_value"
     */
    public function testPropertyArgumentValue()
    {

    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {

    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {

    }

    /**
     * Test attribute "first_party_id"
     */
    public function testPropertyFirstPartyId()
    {

    }

    /**
     * Test attribute "first_party_type"
     */
    public function testPropertyFirstPartyType()
    {

    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {

    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {

    }

    /**
     * Test attribute "ref_type_id"
     */
    public function testPropertyRefTypeId()
    {

    }

    /**
     * Test attribute "second_party_id"
     */
    public function testPropertySecondPartyId()
    {

    }

    /**
     * Test attribute "second_party_type"
     */
    public function testPropertySecondPartyType()
    {

    }

    /**
     * Test attribute "tax_amount"
     */
    public function testPropertyTaxAmount()
    {

    }

    /**
     * Test attribute "tax_reciever_id"
     */
    public function testPropertyTaxRecieverId()
    {

    }

}
